export const LIMITS = {
  POST_TITLE_MIN: 3,
  POST_TITLE_MAX: 160,
  POST_EXCERPT_MAX: 280,
  POST_CONTENT_MIN: 1,
  COMMENT_MAX: 2000,
  NICKNAME_MIN: 3,
  NICKNAME_MAX: 32,
  BIO_MAX: 500,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 128,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;
